apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: supporttools
  name: lb
spec:
  rules:
  - host: master-BUILD_NUMBER.support.tools
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 80
        pathType: ImplementationSpecific