apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: website
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prod.support.tools,www.support.tools,support.tools
    external-dns.alpha.kubernetes.io/ttl: "120"    
  name: lb
spec:
  tls:
  - hosts:
      - prod.support.tools
      - www.support.tools
      - support.tools
    secretName: support-tools-tls
  rules:
  - host: prod.support.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www
            port:
              name: http
  - host: www.support.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www
            port:
              name: http
  - host: support.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www
            port:
              name: http                            