apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: website
  annotations:
    external-dns.alpha.kubernetes.io/hostname: staging.support.tools
    external-dns.alpha.kubernetes.io/ttl: "120"    
  name: lb
spec:
  tls:
  - hosts:
      - staging.support.tools
    secretName: support-tools-tls
  rules:
  - host: staging.support.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www
            port:
              name: http