---
kind: pipeline
type: kubernetes
name: SupportTools

steps:
  - name: build-docker
    image: plugins/docker
    settings:
      repo: supporttools/website
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

  - name: customize-kube-files
    image: supporttools/kube-builder
    pull: true
    environment:
      APPENV: ${DRONE_COMMIT_BRANCH}
    commands:
      - bash ./deploy.sh

  - name: deploy-nonprod
    image: cube8021/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server_npd
      kubernetes_token:
        from_secret: k8s_token_npd
    commands:
      - kubectl create ns supporttools-website-${DRONE_BUILD_NUMBER}
      - kubectl apply -n supporttools-website-${DRONE_BUILD_NUMBER} -f ./deployment-ready/

  - name: deploy-staging
    image: cube8021/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server_stage
      kubernetes_token:
        from_secret: k8s_token_stage
    commands:
      - kubectl create ns supporttools-website-staging
      - kubectl apply -n supporttools-website-staging -f ./deployment-ready/
    when:
     event:
     - deployment
     - promote
     environment: staging

  - name: deploy-prd-b
    image: cube8021/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server_prod
      kubernetes_token:
        from_secret: k8s_token_prod
    commands:
      - kubectl create ns supporttools-website-production
      - kubectl apply -n supporttools-website-production -f ./deployment-ready/
    when:
     event:
     - deployment
     - promote
     environment: production
