---
kind: pipeline
type: kubernetes
name: SupportTools-Build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      registry: a1-harbor.support.tools
      repo: a1-harbor.support.tools/supporttools/website
      cache_from: "a1-harbor.support.tools/supporttools/website:latest"
      dry_run: true
      purge: false
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest      

  - name: Docker-Publish
    image: plugins/docker
    settings:
      registry: a1-harbor.support.tools
      repo: a1-harbor.support.tools/supporttools/website
      cache_from: "a1-harbor.support.tools/supporttools/website:latest"
      purge: false
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: harbor-username
      password:
        from_secret: harbor-password
    when:
     event:
     - deployment
     - promote

  - name: Customize-kube-files
    image: supporttools/kube-builder
    pull: true
    environment:
      APPENV: ${DRONE_COMMIT_BRANCH}
    commands:
      - bash ./deploy.sh

  - name: Deploy-to-Dev
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    commands:
      - kubectl apply -n supporttools-website-dev -f ./deployment-ready/
    when:
     event:
     - deployment
     - promote
     target:
     - dev

  - name: Deploy-to-Staging
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    commands:
      - kubectl apply -n supporttools-website-staging -f ./deployment-ready/
    when:
     event:
     - deployment
     - promote
     target:
     - staging

  - name: Deploy-to-Production
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    commands:
      - kubectl apply -n supporttools-website-production -f ./deployment-ready/
    when:
     event:
     - deployment
     - promote
     target:
     - production

node_selector:
  drone-runner: true

image_pull_secrets:
- regcreds