---
kind: pipeline
type: kubernetes
name: SupportTools-Build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/website
      cache_from: "supporttools/website:latest"
      dry_run: true
      purge: false
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest      

  - name: Docker-Publish
    image: plugins/docker
    settings:
      repo: supporttools/website
      cache_from: "supporttools/website:latest"
      purge: false
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote

  - name: Customize-kube-files
    image: supporttools/kube-builder:32
    pull: true
    environment:
      APPENV: ${DRONE_COMMIT_BRANCH}
    commands:
      - bash ./deploy.sh

- name: Deploy-to-Master
    image: supporttools/kube-builder:latest
    settings:
      kubernetes_server:
        from_secret: k8s_server_a1-rke-dev
      kubernetes_token:
        from_secret: k8s_token_a1-rke-dev
    commands:
      - kubectl create ns supporttools-website-master-${CI_BUILD_NUMBER}
      - kubectl label ns supporttools-website-master-${CI_BUILD_NUMBER} team=supporttools --overwrite
      - kubectl label ns supporttools-website-master-${CI_BUILD_NUMBER} app=supporttools-www --overwrite
      - kubectl label ns supporttools-website-master-${CI_BUILD_NUMBER} ns-purge=true --overwrite
      - kubectl label ns supporttools-website-master-${CI_BUILD_NUMBER} team=supporttools --overwrite
      - kubectl apply -n supporttools-website-master-${CI_BUILD_NUMBER} -f ./deployment-ready/
      - kubectl apply -n supporttools-website-master-${CI_BUILD_NUMBER} -f ./deployment/ingress/dev.yaml

  - name: Deploy-to-Dev
    image: supporttools/kube-builder:latest
    settings:
      kubernetes_server:
        from_secret: k8s_server_a1-rke-dev
      kubernetes_token:
        from_secret: k8s_token_a1-rke-dev
    commands:
      - kubectl apply -n supporttools-website-dev -f ./deployment-ready/
      - kubectl apply -n supporttools-website-dev -f ./deployment/ingress/dev.yaml
    when:
     event:
     - deployment
     - promote
     target:
     - dev

  - name: Deploy-to-Staging
    image: supporttools/kube-builder:latest
    settings:
      kubernetes_server:
        from_secret: k8s_server_b1-rke-prd
      kubernetes_token:
        from_secret: k8s_token_b1-rke-prd
    commands:
      - kubectl apply -n supporttools-website-staging -f ./deployment-ready/
      - kubectl apply -n supporttools-website-staging -f ./deployment/ingress/staging.yaml
    when:
     event:
     - deployment
     - promote
     target:
     - staging

  - name: Deploy-to-Production
    image: supporttools/kube-builder:latest
    settings:
      kubernetes_server:
        from_secret: k8s_server_b1-rke-prd
      kubernetes_token:
        from_secret: k8s_token_b1-rke-prd
    commands:
      - kubectl apply -n supporttools-website-production -f ./deployment-ready/
      - kubectl apply -n supporttools-website-production -f ./deployment/ingress/production.yaml
    when:
     event:
     - deployment
     - promote
     target:
     - production

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true

image_pull_secrets:
- regcred