---
kind: pipeline
type: kubernetes
name: SupportTools

steps:
- name: publish
  image: banzaicloud/drone-kaniko
  settings:
    registry: registry-private.support.tools # if not provided index.docker.io is supposed
    repo: supporttools/website
    tags: ${DRONE_BUILD_NUMBER}
    cache: true
    skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
    username:
      from_secret: docker-username
    password:
      from_secret: docker-password
