---
kind: pipeline
name: pull-request

platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  image: plugins/docker
  settings:
    context: ./
    tags: ${DRONE_BUILD_NUMBER}
    repo: registry-private.support.tools/supporttools/website
    registry: registry-private.support.tools
    repo: supporttools/website
    password:
      from_secret: Docker_Repo_Password
    username:
      from_secret: Docker_Repo_Username
  when:
    event:
    - pull_request
    - push
