FROM alpine AS hugo-builder

# Install Hugo
RUN apk add --no-cache hugo

# Copy the source code
COPY ./blog/ /site

# Set the working directory
WORKDIR /site

# Build the site
RUN hugo --minify --gc --cleanDestinationDir --baseURL https://support.tools

# Stage 2: Build the Go application and prepare runtime environment
FROM golang:1.22.4-alpine3.20 AS go-builder

# Install git if your project requires
RUN apk update && apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /src

# Copy the source code into the container
COPY . .

# Fetch dependencies using go mod if your project uses Go modules
RUN go mod download

# Version and Git Commit build arguments
ARG VERSION
ARG GIT_COMMIT
ARG BUILD_DATE

# Build the Go app with versioning information
RUN GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/supporttools/website/pkg/version.Version=$VERSION -X github.com/supporttools/website/pkg/version.GitCommit=$GIT_COMMIT -X github.com/supporttools/website/pkg/version.BuildTime=$BUILD_DATE" -o /bin/webserver
RUN chmod +x /bin/webserver

# Stage 3: Prepare final runtime image
#FROM scratch
FROM ubuntu

# Set the working directory to /app
WORKDIR /app

# Copy the built binary from the go-builder stage
COPY --from=go-builder /bin/webserver /app/webserver

# Copy the website from the hugo-builder stage
COPY --from=hugo-builder /site/public /app/public

# Copy the /etc/passwd file from the builder stage to run as a non-root user
COPY --from=0 /etc/passwd /etc/passwd

# Copy the sitemap.xml generated by Hugo
COPY --from=hugo-builder /site/public/sitemap.xml /app/public/sitemap.xml

# User appuser to run the container securely
USER appuser

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/app/webserver"]
