name = "support-tools"
main = "src/worker.js"
compatibility_date = "2025-01-13"
compatibility_flags = ["nodejs_compat"]
account_id = "d2264bbcd4403af8321dab6b9dd66dad"

# Enable Workers Logs
[observability]
enabled = true

# Static assets configuration
[assets]
directory = "./blog/public"
binding = "ASSETS"

[env.production]
name = "support-tools"
routes = [
  { pattern = "support.tools/*", zone_id = "fde9d47ab90d79ebdce1e1825880ea79" }
]

[env.staging]
name = "support-tools-staging"
routes = [
  { pattern = "stg.support.tools/*", zone_id = "fde9d47ab90d79ebdce1e1825880ea79" }
]

[env.development]
name = "support-tools-dev"
routes = [
  { pattern = "dev.support.tools/*", zone_id = "fde9d47ab90d79ebdce1e1825880ea79" }
]

[env.mst]
name = "support-tools-mst"
routes = [
  { pattern = "mst.support.tools/*", zone_id = "fde9d47ab90d79ebdce1e1825880ea79" }
]

[env.qas]
name = "support-tools-qas"
routes = [
  { pattern = "qas.support.tools/*", zone_id = "fde9d47ab90d79ebdce1e1825880ea79" }
]

[env.tst]
name = "support-tools-tst"
routes = [
  { pattern = "tst.support.tools/*", zone_id = "fde9d47ab90d79ebdce1e1825880ea79" }
]