apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-tls
spec:
  secretName: website-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host | quote }}
  dnsNames:
  - {{ .Values.ingress.host | quote }}