apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  labels:
    app: website
    team: supporttools
    component: website
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: website
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: website-tls