apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
    component: frontend
    team: SupportTools
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: website
    component: frontend
    team: SupportTools