apiVersion: v1
kind: Service
metadata:
  name: web-cache
  labels:
    app: website
    component: web-cache
    team: SupportTools
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9001
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: website
    component: web-cache
    team: SupportTools