apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
    team: SupportTools
    component: website
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: website
    team: SupportTools
    component: website