apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: cf-tunnel
subjects:
  - kind: Service
    name: website-tunnel
    spec:
      fqdn: {{ .Values.ingress.host | quote }}
      protocol: http
      target: http://website.{{ .Release.Namespace }}.svc.cluster.local:8080
      noTlsVerify: false
tunnelRef:
  kind: ClusterTunnel
  name: support-tools-tunnel
  disableDNSUpdates: false
