baseURL = "/"
title = "Support Tools"
theme = "m10c"
pagination.pagerSize = 8 # Updated from paginate

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "certificates"
    name = "Certificates"
    url = "/certificates/"
    weight = 4

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 5

  [[menu.main]]
    identifier = "training"
    name = "Training"
    url = "/training/"
    weight = 6

  [[menu.main]]
    identifier = "known-good-designs"
    name = "Known Good Designs"
    url = "/known-good-designs/"
    weight = 7

[params]
  author = "Matthew Mattox"
  description = "Matthew Mattox Personal Tech Blog"
  avatar = "https://cdn.support.tools/profiles/avatar-centered.png"
  menu_item_separator = " - "

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/mattmattox"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/cube8021"

  [[params.social]]
    icon = "brand-bluesky"
    name = "BlueSky"
    url = "https://bsky.app/profile/support.tools"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/matthewmattox/"

  [[params.social]]
    icon = "reddit"
    name = "Reddit"
    url = "https://www.reddit.com/user/cube8021/"

  googleAnalytics = "UA-151436906-1"

# Uncomment one of the following style sections to customize the theme colors.

# Default theme
#[params.style]
#  darkestColor = "#242930"
#  darkColor = "#353b43"
#  lightColor = "#afbac4"
#  lightestColor = "#ffffff"
#  primaryColor = "#57cc8a"

# Green theme
#[params.style]
#  darkestColor = "#315659"
#  darkColor = "#253031"
#  lightColor = "#96a879"
#  lightestColor = "#fff"
#  primaryColor = "#dad865"

# Red theme
#[params.style]
#  darkestColor = "#d35050"
#  darkColor = "#212121"
#  lightColor = "#d6d6d6"
#  lightestColor = "#d3d3d3"
#  primaryColor = "#ffffff"
