baseURL = "/"
title = "Support Tools"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "certificates"
    name = "Certificates"
    url = "/certificates/"
    weight = 3
  [[menu.main]]
    identifier = "kubernetes"
    name = "Kubernetes"
    url = "/categories/rancher/"
    weight = 4
  [[menu.main]]
    identifier = "rancher"
    name = "Rancher"
    url = "/categories/rancher/"
    weight = 5
  [[menu.main]]
    identifier = "ubuntu"
    name = "Ubuntu"
    url = "/categories/ubuntu/"
    weight = 6

[params]
  author = "Matthew Mattox"
  description = "Matthew Mattox Personal Tech Blog"
  avatar = "/images/avatar-shifted_down.png"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/mattmattox"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/cube8021"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"