baseURL = "/"
title = "Support Tools"
theme = "m10c"
pagination.pagerSize = 8  # Updated from paginate

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "certificates"
    name = "Certificates"
    url = "/certificates/"
    weight = 3

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 4

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 5

  [[menu.main]]
    identifier = "training"
    name = "Training"
    url = "/training/"
    weight = 6

  [[menu.main]]
    identifier = "fleet"
    name = "Fleet"
    url = "/training/fleet/"
    parent = "training"
    weight = 7

  [[menu.main]]
    identifier = "rancher"
    name = "Rancher"
    url = "/training/rancher/"
    parent = "training"
    weight = 8

  [[menu.main]]
    identifier = "rke"
    name = "RKE"
    url = "/training/rke/"
    parent = "training"
    weight = 9

  [[menu.main]]
    identifier = "rke2"
    name = "RKE2"
    url = "/training/rke2/"
    parent = "training"
    weight = 10

  [[menu.main]]
    identifier = "kubernetes"
    name = "Kubernetes"
    url = "/categories/kubernetes/"
    weight = 11

  [[menu.main]]
    identifier = "ubuntu"
    name = "Ubuntu"
    url = "/categories/ubuntu/"
    weight = 12

  [[menu.main]]
    identifier = "known-good-designs"
    name = "Known Good Designs"
    url = "/known-good-designs/"
    weight = 13    

[params]
  author = "Matthew Mattox"
  description = "Matthew Mattox Personal Tech Blog"
  avatar = "https://cdn.support.tools/profiles/avatar-centered.png"
  menu_item_separator = " - "

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/mattmattox"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/cube8021"

  googleAnalytics = "UA-151436906-1"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
