baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Support Tools - Matthew Mattox"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "Matthew Mattox Personal Site"
  author = "Matthew Mattox"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Rancher"
identifier = "ds"
url = "/categories/rancher/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Kubernetes"
identifier = "ds"
url = "/categories/kubernetes/"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Ubuntu"
identifier = "ds"
url = "/categories/ubuntu/"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> About Me"
identifier = "ds"
url = "/about"
weight = 13

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Certificates"
identifier = "ds"
url = "/certificates"
weight = 14
