apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: supporttools
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Support.Tools
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
