apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supporttools-qas
spec:
  destination:
    namespace: supporttools-qas
    server: https://kubernetes.default.svc
  project: supporttools
  source:
    chart: website
    helm:
      parameters:
        - name: ingress.host
          value: qas.support.tools
    repoURL: https://charts.support.tools
    targetRevision: CHARTVERSION
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: "30m"
        factor: 2
        maxDuration: "5m"
