apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: support-tools-tls
spec:
  secretName: support-tools-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 'staging.support.tools'
  dnsNames:
  - staging.support.tools