name: Build

on:
  [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: HUGO test build
        run: |
          cd blog/
          docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 --panicOnWarning --baseUrl http://localhost/
          sudo chown -R $USER:$USER public/
          mv public/ ../../
          cd ../../
      
      - name: html-validation
        run: |
          cd blog/
          docker run --rm -v $(pwd):/src -w /src thegeeklab/vnu vnu --skip-non-html --errors-only --filterfile .vnuignore public/

      - name: Checking for draft content
        run: |
          grep -R 'draft: true' blog/content/post && exit 1 || exit 0
      
      - name: Checking for orphaned content
        run: |
          cd blog/
          docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 list orphan

      - name: Checking for dead links
        run: |
          cd blog/
          docker run --rm -v $(pwd):/src -w /src -e LINK_VALIDATOR_BASE_DIR="/src/blog/public" -e LINK_VALIDATOR_RETRIES=3 thegeeklab/link-validator --color=always --rate-limit 10 -e https://support.tools

      - name: Docker build
        run: |
          cd blog/
          docker build -t supporttools/website:latest .

      - name: Docker push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push supporttools/website:latest



      
      
