name: Build

on:
  [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: HUGO test build
        run: |
          CWPD=$(pwd)
          cd blog/
          docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 --panicOnWarning --baseUrl http://localhost/
          sudo mv public/ $CWPD/
      
      - name: html-validation
        run: |
           docker run --rm -v $(pwd):/src -w /src thegeeklab/vnu vnu --skip-non-html --errors-only --filterfile .vnuignore public/

      - name: Checking for draft content
        run: |
          CWPD=$(pwd)
          cd blog/
          if [[ -z `docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 list drafts | grep -v '_template.md'` ]] 
          then
            echo "Draft content found"
            exit 1
          else
            echo "No draft content found"
          fi
      
      - name: Checking for orphaned content
        run: |
          cd blog/
          docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 list orphan

      - name: Checking for dead links
        run: |
          cd blog/
          docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 --quiet --baseUrl http://localhost/ && docker run --rm -v $(pwd):/src -w /src thegeeklab/hugo:0.105 htmlproofer --check-html --disable-external --allow-hash-href --assume-extension --url-ignore "/localhost/,/github.com/,/github.io/,/githubusercontent.com/" ./public
      
      - name: Docker build
        run: |
          cd blog/
          docker build -t supporttools/website:latest .

      - name: Docker push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push supporttools/website:latest



      
      
