name: Build

on:
  [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: HUGO test build
        run: |
          docker run --rm -v $(pwd)/blog/:/src -w /src thegeeklab/hugo:0.122.0 hugo --panicOnWarning --minify --gc --cleanDestinationDir --destination public --baseURL http://localhost
        
      - name: html-validation
        run: |
          docker run --rm -v $(pwd)/blog/:/src -w /src thegeeklab/vnu vnu --skip-non-html --errors-only --filterfile .vnuignore public/

      - name: Checking for draft content
        run: |
          grep -R 'draft: true' blog/content/post && exit 1 || exit 0
      
      - name: Checking for orphaned content
        run: |
          docker run --rm -v $(pwd)/blog/:/src -w /src thegeeklab/hugo:0.105 list orphan

      - name: Docker build
        run: |
          docker build -t supporttools/website:${GITHUB_SHA} .

      - name: Docker push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push supporttools/website:${GITHUB_SHA}

      - name: Deploy-to-Master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          bash deploy.sh

      - name: Deploy-to-Dev
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          docker run --rm -v $(pwd):/src -w /src 
          -e DOCKER_USERNAME=$DOCKER_USERNAME 
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD 
          -e CATTLE_SERVER=$CATTLE_SERVER 
          -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY 
          -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY 
          supporttools/kube-builder:latest 
          bash deploy.sh dev ${GITHUB_SHA}

      - name: Deploy-to-QAS
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          docker run --rm -v $(pwd):/src -w /src 
          -e DOCKER_USERNAME=$DOCKER_USERNAME 
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD 
          -e CATTLE_SERVER=$CATTLE_SERVER 
          -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY 
          -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY 
          supporttools/kube-builder:latest 
          bash deploy.sh qas ${GITHUB_SHA}

      - name: Deploy-to-TST
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          docker run --rm -v $(pwd):/src -w /src 
          -e DOCKER_USERNAME=$DOCKER_USERNAME 
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD 
          -e CATTLE_SERVER=$CATTLE_SERVER 
          -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY 
          -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY 
          supporttools/kube-builder:latest 
          bash deploy.sh tst ${GITHUB_SHA}

      - name: Deploy-to-TST
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          docker run --rm -v $(pwd):/src -w /src 
          -e DOCKER_USERNAME=$DOCKER_USERNAME 
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD 
          -e CATTLE_SERVER=$CATTLE_SERVER 
          -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY 
          -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY 
          supporttools/kube-builder:latest 
          bash deploy.sh tst ${GITHUB_SHA}

      - name: Deploy-to-STG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          docker run --rm -v $(pwd):/src -w /src 
          -e DOCKER_USERNAME=$DOCKER_USERNAME 
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD 
          -e CATTLE_SERVER=$CATTLE_SERVER 
          -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY 
          -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY 
          supporttools/kube-builder:latest 
          bash deploy.sh stg ${GITHUB_SHA}

      - name: Deploy-to-PRD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CATTLE_SERVER: ${{ secrets.CATTLE_SERVER }}
          CATTLE_ACCESS_KEY: ${{ secrets.CATTLE_ACCESS_KEY }}
          CATTLE_SECRET_KEY: ${{ secrets.CATTLE_SECRET_KEY }}
        run: |
          docker run --rm -v $(pwd):/src -w /src 
          -e DOCKER_USERNAME=$DOCKER_USERNAME 
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD 
          -e CATTLE_SERVER=$CATTLE_SERVER 
          -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY 
          -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY 
          supporttools/kube-builder:latest 
          bash deploy.sh prd ${GITHUB_SHA}          