# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: EthicalCheck-Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Customize trigger events based on your DevSecOps processes.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 3 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    env:
      OAS_URL: "http://netbanking.apisec.ai:8080/v2/api-docs"
      REPORT_EMAIL: "mmattox@support.tools"

    steps:
       - name: EthicalCheck  Free & Automated API Security Testing Service
         uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
         with:
          # The OpenAPI Specification URL or Swagger Path or Public Postman collection URL.
          oas-url: ${{ env.OAS_URL }}
          # The email address to which the penetration test report will be sent.
          email: ${{ env.REPORT_EMAIL }}
          sarif-result-file: "ethicalcheck-results.sarif"

       - name: Upload SARIF file to repository
         uses: github/codeql-action/upload-sarif@v3
         with:
          sarif_file: ./ethicalcheck-results.sarif

       - name: Upload SARIF file as an artifact
         uses: actions/upload-artifact@v3
         with:
          name: ethicalcheck-sarif
          path: ./ethicalcheck-results.sarif

       - name: Send Slack notification
         uses: slackapi/slack-github-action@v1.23.0
         with:
           payload: |
             {
               "text": "EthicalCheck has completed. Check the SARIF file for details."
             }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
