name: Sync CDN to Wasabi

on:
  # Trigger on changes to cdn.support.tools directory
  push:
    paths:
      - 'cdn.support.tools/**'
  
  # Add manual trigger option
  workflow_dispatch:
  
  # Optional: Add ability to call from other workflows
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'production'

jobs:
  sync-to-wasabi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper change detection
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Sync to Wasabi S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
          AWS_REGION: us-central-1
        run: |
          echo "Starting sync of cdn.support.tools to Wasabi"
          aws s3 sync ./cdn.support.tools/ s3://cdn.support.tools/ \
            --endpoint-url=https://s3.us-central-1.wasabisys.com \
            --exclude ".git/*" \
            --acl public-read
          echo "Sync completed successfully"
